import Head from 'next/head';
import { Inter } from 'next/font/google';
import Experience from '@/components/Experience';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <div className="h-full" style={{ height: '50vh' }}></div>
          <Experience />
        </div>
      </main>
    </>
  );
}
